language: c

compiler: gcc

script:
    make
    
notifications:
  email:
    recipients:
      - c.doggen@d-r.nl
    on_success: always # default: change
    on_failure: always # default: always
    
